name: CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  notify:
    uses: ./.github/workflows/notify-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  build:
    uses: ./.github/workflows/python-build.yml
    secrets:
      BASE_PROVIDER_URL: ${{ secrets.BASE_PROVIDER_URL }}

  report:
    if: ${{ always() }}
    needs:
      - notify
      - build
    uses: ./.github/workflows/report-slack.yml
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    with:
      success: ${{ needs.build.result == 'success' }}
      slack-status-msg-id: ${{ needs.notify.outputs.slack-status-msg-id }}
